spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: "mySuperSecretKey12345678901234567890"  # 32+ символов!
  expiration: 3600000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG